### ISSUE TITLE
Detect lack of authorization checks

### ISSUE THREAD

**Issue by DavidMikeSimon** [AmericanCouncils/kalinka-bundle#13]
Using a pattern like in http://symfony.com/doc/current/cookbook/event_dispatcher/before_after_filters.html we should allow app to mark controllers which should authorize all actions, and then check to make sure that an authorization check was made. There should also be a way for actions to explicitly declare that they do not require authorization.

**Comment by evillemez** [comment]
@DavidMikeSimon You can use the "defaults" param to specify extra request attributes on a per-route basis.  Something like this:

``` yaml

some_route_name:
    path: /hello/{name}
    defaults:
        _controller: AcmeHelloBundle:Hello:index
        _kalinka:
            guard: app-controller-guard
            action: someKalinkaActionName

```

The listener would then just do something like:

``` php
<?php

public function onKernelController($event)
{
    $req = $event->getRequest();

    if (!$check = $req->attributes->get('_kalinka', false)) {
        return;
    }

    $auth = $this->container->get('kalinka.authorizor');
    if (!$auth->can($check['guard'], $check['action'], $req)) {
        throw new HttpException(403, "Computer says no. :(");
    }

    //say this req was authorized if we really need to check for it elsewhere
    $req->attributes->set('_kalinka_authorized', true);
}

```

There shouldn't need to be any step for checking if a call was made.  If there really does need to be, we could just add arbitrary app-level attributes on the request in the pre-controller stage in the listener, and check for them later:

``` php
<?php
//...elsewhere
if (!$request->attributes->has('_kalinka_authorized')) {
    //throw new ...
}
```
